routes/web.php
<?php
use App\Post;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/properties', function () {
//
//    $properties = DB::table('properties')->latest()->get();
//
//
//    return view('layouts/index', compact('properties'));
//
//
//});
//Route::get('/properties/{property}', function ($id) {
//
//    $properties = DB::table('properties')->find($id);
//
//    return view('layouts/show', compact('properties'));
//
//});
//
//Route::get('/', function () {
//
//
//    return view('layouts/show');
//
//});

//Updating DB
//Route::get('/update', function() {
//    $updated=DB::update('update users set title = "update title" where id = ?',[1]);
//    return $updated;
//});
//
//Reading DB
//Route::get('/read', function(){
//    $results = DB::select('select * from properties where id =?', [1]);
//
//    foreach($results as $property){
//
//        return $property->title;
//    }
//});

//Deleting from DB
//
//Route::get('/delete', function(){
//
//    $deleted = DB::delete('delete from users where id = ?', [1]);
//
//    return $deleted;
//});

//Home
Route::get('/','HomeController@welcome')->name('welcome');
//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'HomeController@dash')->name('dash');

Auth::routes();

Route::get('tinker', function (){
    return view('js-playground');
});

//Route::get('/home_auth', 'HomeController@index')->name('home');

Route::get('/form', function (){
    return view('form');
});

Route::get('/browse_properties', function (){

    $properties = DB::table('properties')->get();

    return view('browse_properties', ['properties' => $properties]);


});
Route::get('/new-form', 'PropertyController@addProperty')->name('newPropertyForm');

Route::get('/read', function(){
    $posts = Post::all();

    foreach($posts  as $post) {

      return $post->title;

    }
});

Route::get('/find', function(){

    $posts = Post::find(4);
    return $posts->title;

});

Route::get('/findwhere', function(){

    $posts = Post::where('id', 3)->orderBy('id', 'desc')->take(1)->get();
    return $posts;
});

Route::get('/findmore', function(){

    $posts = Post::where('users_count', '<', '50')-> firstOrFail();

    return $posts;

});

Route::get('/basicinsert', function (){

    $post = new Post;

    $post->title = 'James is a legend';
    $post->save();


});

Route::get('/basicinsert2', function (){

    $post = Post::find(1);

    $post->title = 'New inserted title number 1';
    $post->save();


});

Route::get('/create', function(){

    Post::create(['title'=> 'the create method']);
});

Route::get('/update', function(){

    Post::where('id', 3)->where('title', 'is mr')->update(['title'=>'time to update baby']);
});


Route::get('/delete', function(){

    $post = Post::find(2);

    $post-> delete();
});



/*
|--------------------------------------------------------------------------
| Eloquent relationships
|--------------------------------------------------------------------------
*/

//One to one relationship

Route::get('/user/{id}/post', function ($id){

    return User::find($id )->post->content;
});

Route::get('/post/{id}/user', function ($id){

    return Post::find($id)->user->name;
});

//One to many relationship


/*
|--------------------------------------------------------------------------
| CRUD application
|--------------------------------------------------------------------------
*/

Route::resource('posts', 'PostController');

Route::get('/user/{id}/post', function ($user_id){

    return User::find($user_id)->post;

})->name('userPosts');



Route::get('/usersposts', function ()
{

    $posts = Post::where('user_id','=',Auth::user()->id)->paginate(5);

    return view('posts/index', ['posts' => $posts]);

})->name('usersPosts');

//Route::get('/userposts', 'PostController@authPosts')->name('userPosts');


Route::get('/usersposts/{user_id}', function ($user_id)
{

    $posts = Post::where('user_id','=',$user_id)->paginate(5);

    return view('posts/index', ['posts' => $posts]);

})->name('usersPosts');



Route::post('favourite/{post}', 'PostController@favouritePost');
Route::post('unfavourite/{post}', 'PostController@unFavouritePost');

Route::get('my_favourites', 'UsersController@myFavourites')->middleware('auth');

resources/views/form.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{{ asset('css/quiz.css') }}" rel="stylesheet">

{{--action="{{route ('upload')}}"--}}
    <form action="{{route('newPropertyForm')}}">
        {{--House numbr--}}
        <div class="form-group">
            <label for="houseNumber">House number or name</label>
            <input type="text" class="form-control" id="houseNumber" placeholder="1">
        </div>
        {{--Post code--}}
        <div class="form-group">
            <label for="postCode">Post code</label>
            <input type="text" class="form-control" id="postCode" placeholder="EX1 ABC">
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="propertyTypeRadios" id="propertyTypeRadioHouse" value="option1" checked>
            <label class="form-check-label" for="propertyTypeRadioHouse">
                house
            </label>
        </div>
        {{--Type of property--}}
        <div class="form-check">
            <input class="form-check-input" type="radio" name="propertyTypeRadios" id="propertyTypeRadioFlat" value="option2">
            <label class="form-check-label" for="propertyTypeRadioFlat">
                flat
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="propertyTypeRadios" id="propertyTypeRadioCommercial" value="option3">
            <label class="form-check-label" for="propertyTypeRadioBungalow">
                commercial
            </label>
        </div>
        {{--Price--}}
        <div class="form-group">
            <label for="propertyPrice">Price</label>
            <input type="number" class="form-control" id="propertyPrice" placeholder="£100000">
        </div>
        {{--Number of bathrooms--}}
        <div class="form-group">
            <label for="propertyBathNumber">Number of bathrooms</label>
            <select class="form-control" id="propertyBathNumber">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6+</option>
            </select>
        </div>
        {{--Number of bedrooms--}}
        <div class="form-group">
            <label for="propertyBedNumber">Number of bedrooms</label>
            <select class="form-control" id="propertyBedNumber">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8+</option>
            </select>
        </div>
        <div class="form-group">
            <label for="propertyDescription">Example textarea</label>
            <textarea class="form-control" id="propertyDescription" rows="6"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>



        </div>
    </div>

</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
{{--<!doctype html>--}}
{{--<html lang="en">--}}
{{--<head>--}}
    {{--<!-- Required meta tags -->--}}
    {{--<meta charset="utf-8">--}}
    {{--<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">--}}

    {{--<!-- Bootstrap CSS -->--}}
    {{--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"--}}
          {{--integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">--}}
    {{--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"--}}
          {{--integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">--}}
    {{--<link rel="stylesheet" type="text/css" href="/css/style.css">--}}

    {{--<title>Home</title>--}}
{{--</head>--}}
{{--<body>--}}

{{--<!--Navbar//////////////////////////////////////////////////////-->--}}
{{--<nav class="navbar navbar-expand-lg">--}}
    {{--<!--<a class="navbar-brand" href="#"></a>-->--}}
    {{--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"--}}
            {{--aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">--}}
        {{--<span class="navbar-toggler-icon"></span>--}}
    {{--</button>--}}

    {{--<div class="collapse navbar-collapse" id="navbarSupportedContent">--}}
        {{--<ul class="navbar-nav mr-auto">--}}
            {{--<li class="nav-item active">--}}
                {{--<a class="nav-link" href="homePage.html">Home</a>--}}
            {{--</li>--}}
            {{--<li class="nav-item">--}}
                {{--<a class="nav-link" href="#about">About</a>--}}
            {{--</li>--}}
            {{--<li class="nav-item">--}}
                {{--<a class="nav-link" href="contact.html">Contact</a>--}}
            {{--</li>--}}

        {{--</ul>--}}
        {{--<ul class="navbar-nav">--}}
            {{--<a class="nav-link" id="nav_signup" href="/register">Sign Up</a>--}}
            {{--<a class="nav-link" href="/login">Log in</a>--}}
            {{--<li><a href="{{ route('login') }}">Login</a></li>--}}
        {{--</ul>--}}

    {{--</div>--}}

{{--</nav>--}}


@extends('layouts.app')

@section('content')
<!--Home Landing page////////////////////////////////////////////////-->
<div class="container-fluid home">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <h1>Deal combinator</h1>
                <h3>Where deals are made</h3>
                <hr>
                <button type="button" class="btn btn-secondary btn-lg">Get started</button>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row what_we_do" id="about">
        <div class="col-lg-12">
            <h1>Why deal combinator?</h1>
        </div>
    </div>
    <div class="row what_we_do">
        <div class="col-lg-3">
            <i class="fas fa-lock icons"></i>
            <h2>Safe and secure</h2>
            <p>Securely uplpoad your deals onto the website and add as little or as much information as you choose. Also, check the track record of whoever you do business with.</p>
        </div>
        <div class="col-lg-3">
            <i class="fas fa-search icons"></i>
            <h2>Browse thousands of deals</h2>
            <p>Use our search tools ot browse thousands of deals from reputable deal sourcers and find those that are right for you.</p>

        </div>
        <div class="col-lg-3">
            <i class="fas fa-expand-arrows-alt icons"></i>
            <h2>Grow your network</h2>
            <p>Make connections and message other investors and sourcers online to make grow your business and your network</p>

        </div>
        <div class="col-lg-3">
            <i class="far fa-handshake icons"></i>
            <h2>Make more deals</h2>
            <p>With thousands of deals available you will be abe to easily find what your looking for and find all the details you ned in on place</p>


        </div>

    </div>
</div>
<div class="container-fluid how_it_works">
    <div class="row">
        <div class="col-lg-12">
            <h1>How it works</h1>
            <h6>for investors...</h6>
        </div>
    </div>
    <div class="row how_it_works">
        <div class="col-lg-6 ">
            <h3>hello world</h3>
        </div>
        <div class="col-lg-6 steps">
            <div>1</div>
            <p>Sign up</p>
            <div>2</div>
            <p>Upload deals online</p>
            <div>3</div>
            <p>Reply to investors and message investors to build custom deals</p>
            <a href="#" class="btn_app">
                <img src="/images/logo-app_store.png" class="btn-app">
            </a>
            <a href="#" class="btn_app">
                <img src="/images/googleplay.png" class="btn-app">
            </a>

        </div>
    </div>


</div>
<div class="container-fluid how_works sourcers">
    <div class="row how_it_works sourcers">
        <div class="col-lg-12">
            <h1>How it works</h1>
            <h6>for sourcers...</h6>
        </div>
    </div>
    <div class="row how_it_works sourcers">
        <div class="col-lg-6 ">
            <h3>hello world</h3>
        </div>
        <div class="col-lg-6 steps">
            <div>1</div>
            <p>Sign up</p>
            <div>2</div>
            <p>Browse the deals in your area</p>
            <div>3</div>
            <p>Become a member to message the sourcer and get full information</p>
            <a href="#" class="btn_app">
                <img src="/images/logo-app_store.png" class="btn-app">
            </a>
            <a href="#" class="btn_app">
                <img src="/images/googleplay.png" class="btn-app">
            </a>

        </div>


    </div>


</div>
<div class="container-fluid testimonials">
    <div class="row">
        <div class="col-lg-12">
            <h4>Our results speak for themselves</h4>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-4">
            <blockquote>
                Since joining DealCombinator I have been avle to grwo my networking and make more deals than ever before. It is now an essential tool in my business.
                <cite><img src="/images/person_1.jpg" alt="Customer 3 Photo">Harrison Stevens</cite>
            </blockquote>

        </div>
        <div class="col-lg-4">
            <blockquote>
                As a new investor I did not have any network, but Deal Combinator gave me the confidence and the resources to meet many like minded people and make my first deal.
                <cite><img src="/images/person_2.jpeg" alt="Customer 3 Photo">Sarah Milton</cite>
            </blockquote>

        </div>
        <div class="col-lg-4">
            <blockquote>
                I couldn't imagine life without it!
                <cite><img src="/images/person_3.jpg" alt="Customer 3 Photo">Josh Ryan</cite>
            </blockquote>

        </div>
    </div>

</div>
<div class="container-fluid" id="plans">
    <div class="row">
        <div class="col-lg-12 section_plans">
            <h4>Improve your deals today</h4>
        </div>
    </div>
    <div class="row plans_group">
        <div class="col-lg-4 section_plans">
            <div class="plan-box">
                <div>
                    <h3>Master</h3>
                    <p class="plan-price">£399 <span>/ month</span></p>
                </div>
                <div>
                    <ul>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                    </ul>
                </div>
                <div>
                    <a href="#" btn>Sign up now</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 section_plans">
            <div class="plan-box">
                <div>
                    <h3>Pro</h3>
                    <p class="plan-price">£399 <span>/ month</span></p>
                </div>
                <div>
                    <ul>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-times"></i></li>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                    </ul>
                </div>
                <div>
                    <a href="#" class="btn">Sign up now</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 section_plans">
            <div class="plan-box">
                <div>
                    <h3>Starter</h3>
                    <p class="plan-price">£399 <span>/ month</span></p>
                </div>
                <div>
                    <ul>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-check"></i>nwwnnneiw</li>
                        <li><i class="fas fa-times"></i></li>
                        <li
                        <i class="fas fa-times"></i></li>
                    </ul>
                </div>
                <div>
                    <a href="#" class="plan_btn">Sign up now</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="container-fluid">
    <div class="container contactForm">
        <form>
            <div class="row">
                <div class="col-lg-6">
                    <div class="col">
                        <label>First name</label>
                        <input type="text" class="form-control" placeholder="First name">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="col">
                        <label>Last name</label>
                        <input type="text" class="form-control" placeholder="Last name">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>Email address</label>
                <input type="email" class="form-control" placeholder="name@example.com">
            </div>
            <div class="form-group">
                <label>Example multiple select</label>
                <select multiple class="form-control">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Example textarea</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
        </form>
    </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstra2p JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
@endsection

{{--</body>--}}
{{--</html>--}}

resources/views/investorDashboard.blade.php
{{--<!DOCTYPE html>--}}
{{--<html lang="en">--}}
{{--<head>--}}
    {{--<meta charset="UTF-8">--}}
    {{--<title>Dashboard</title>--}}
    {{--<!-- Bootstrap CSS -->--}}
    {{--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"--}}
          {{--integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">--}}
    {{--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"--}}
          {{--integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">--}}
    {{--<link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">--}}
{{--</head>--}}
@extends('layouts.app')
@section('content')
<body id="dashboard">


<div class="container-fluid user-dashboard ">
    <div class="container-fluids dash-header">
        <h1>Hello, James</h1>
        <p>Lets make some deals</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="dash-icons">
                    <i class="fas fa-search icons-dash"></i>
                </div>

                <div class="dash-box">
                    <p>Browse</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="dash-icons">
                    <i class="fas fa-star icons-dash"></i>
                </div>

                <div class="dash-box">
                    <p>Favourites</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="dash-icons">
                    <i class="fas fa-user-edit icons-dash"></i>
                </div>

                <div class="dash-box">
                    <p>Edit profile</p>
                </div>
            </div>
        </div>
        <div class="row half-circle dash-message-container">
            <div class="col-lg-12">
                <div class="dash-icons dash-message">
                    <i class="fas fa-comments dash-message-icons"></i>
                </div>

                <div class="dash-box-message">
                    <p>Messages</p>
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
{{--</html>--}}
    @endsection

resources/views/my_favourites.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h2>My Favourites</h2>
                </div>
                @forelse ($myFavourites as $myFavourite)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {{ $myFavourite->title }}
                        </div>
                        <div class="panel-body " id="favs">
                            @if($myFavourite->property_type ==='House')
                                <img src="/images/house.jpeg">
                            @elseif($myFavourite->property_type ==='Flat')
                                <img src="/images/flat.jpg">
                            @elseif($myFavourite->property_type ==='Land')
                                <img src="/images/land1.jpeg">
                            @elseif($myFavourite->property_type ==='Bungalow')
                                <img src="/images/bungalow.jpg">
                            @elseif($myFavourite->property_type ==='Commercial')
                                <img src="/images/commercial.jpeg">
                            @else
                                <img src="/images/house.jpeg">
                            @endif
                            <ul>
                                <li><i class="fas fa-bath listing-icon"></i>
                                    <p>{{$myFavourite->bathrooms_no}}</p></li>
                                <li><i class="fas fa-bed listing-icon"></i>
                                    <p>{{$myFavourite->beds_no}}</p></li>
                                <div class="price-p row">
                                    <div class="col-lg-4">
                                        <span class="red">Price:</span>
                                        <p> £{{$myFavourite->price}}</p>
                                    </div>
                                    <div class="col-lg-4">
                                        <span class="red">Commision:</span>
                                        <p> £{{$myFavourite->commission}}</p>
                                    </div>


                                </div>
                            </ul>
                        </div>
                        <div class="panel-links">
                            <p>{{{$myFavourite->description}}} <a href="{{route('posts.show', $myFavourite->id)}}"> Read
                                    more</a></p>
                            <p>Listed by: <a
                                        href="{{url("/usersposts/$myFavourite->user_id")}}">{{ $myFavourite->user->name }}</a>
                            </p>
                        </div>


                        @if (Auth::check())
                            <div class="panel-footer">
                                <favourite
                                        post="{{ $myFavourite->id }}"
                                        favourited="{{ $myFavourite->favourited() ? 'true' : '' }}"
                                ></favourite>
                            </div>
                        @endif

                    </div>
                @empty
                    <p>You have no favourite posts.</p>
                @endforelse
                <div class="row listing-links">
                    <button class="btn" onclick="goBack()">Go Back</button>

                    @if(Auth::user()->role === 'sourcer')
                        @if($myFavourite->count() < 1)

                            <a class="btn new-listings" href="{{url('/posts')}}">Favourite a listing</a>
                        @else
                            <a class="btn new-listings" href="{{url('/posts')}}">See more listings</a>
                        @endif

                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection