routes/web.php
<?php
use App\Post;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/properties', function () {
//
//    $properties = DB::table('properties')->latest()->get();
//
//
//    return view('layouts/index', compact('properties'));
//
//
//});
//Route::get('/properties/{property}', function ($id) {
//
//    $properties = DB::table('properties')->find($id);
//
//    return view('layouts/show', compact('properties'));
//
//});
//
//Route::get('/', function () {
//
//
//    return view('layouts/show');
//
//});

//Updating DB
//Route::get('/update', function() {
//    $updated=DB::update('update users set title = "update title" where id = ?',[1]);
//    return $updated;
//});
//
//Reading DB
//Route::get('/read', function(){
//    $results = DB::select('select * from properties where id =?', [1]);
//
//    foreach($results as $property){
//
//        return $property->title;
//    }
//});

//Deleting from DB
//
//Route::get('/delete', function(){
//
//    $deleted = DB::delete('delete from users where id = ?', [1]);
//
//    return $deleted;
//});

//Home
Route::get('/','HomeController@welcome')->name('welcome');
//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'HomeController@dash')->name('dash');

Auth::routes();

Route::get('tinker', function (){
    return view('js-playground');
});

//Route::get('/home_auth', 'HomeController@index')->name('home');

Route::get('/form', function (){
    return view('form');
});

Route::get('/browse_properties', function (){

    $properties = DB::table('properties')->get();

    return view('browse_properties', ['properties' => $properties]);


});
Route::get('/new-form', 'PropertyController@addProperty')->name('newPropertyForm');

Route::get('/read', function(){
    $posts = Post::all();

    foreach($posts  as $post) {

      return $post->title;

    }
});

Route::get('/find', function(){

    $posts = Post::find(4);
    return $posts->title;

});

Route::get('/findwhere', function(){

    $posts = Post::where('id', 3)->orderBy('id', 'desc')->take(1)->get();
    return $posts;
});

Route::get('/findmore', function(){

    $posts = Post::where('users_count', '<', '50')-> firstOrFail();

    return $posts;

});

Route::get('/basicinsert', function (){

    $post = new Post;

    $post->title = 'James is a legend';
    $post->save();


});

Route::get('/basicinsert2', function (){

    $post = Post::find(1);

    $post->title = 'New inserted title number 1';
    $post->save();


});

Route::get('/create', function(){

    Post::create(['title'=> 'the create method']);
});

Route::get('/update', function(){

    Post::where('id', 3)->where('title', 'is mr')->update(['title'=>'time to update baby']);
});


Route::get('/delete', function(){

    $post = Post::find(2);

    $post-> delete();
});



/*
|--------------------------------------------------------------------------
| Eloquent relationships
|--------------------------------------------------------------------------
*/

//One to one relationship

Route::get('/user/{id}/post', function ($id){

    return User::find($id )->post->content;
});

Route::get('/post/{id}/user', function ($id){

    return Post::find($id)->user->name;
});

//One to many relationship


/*
|--------------------------------------------------------------------------
| CRUD application
|--------------------------------------------------------------------------
*/

Route::resource('posts', 'PostController');

Route::get('/user/{id}/post', function ($user_id){

    return User::find($user_id)->post;

})->name('userPosts');



Route::get('/usersposts', function ()
{

    $posts = Post::where('user_id','=',Auth::user()->id)->paginate(5);

    return view('posts/index', ['posts' => $posts]);

})->name('usersPosts');

//Route::get('/userposts', 'PostController@authPosts')->name('userPosts');


Route::get('/usersposts/{user_id}', function ($user_id)
{

    $posts = Post::where('user_id','=',$user_id)->paginate(5);

    return view('posts/index', ['posts' => $posts]);

})->name('usersPosts');



Route::post('favourite/{post}', 'PostController@favouritePost');
Route::post('unfavourite/{post}', 'PostController@unFavouritePost');

Route::get('my_favourites', 'UsersController@myFavourites')->middleware('auth');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;




class Post extends Model
{
    //


    public $timestamps = false;

    protected $fillable =[

        'user_id',
        'title',
        'content',
        'post_code',
        'house_number',
        'property_type',
        'beds_no',
        'bathrooms_no',
        'price',
        'commission',
        'description',
        'image_pathway',

    ];

    public function user() {

    return $this->belongsTo('App\User');

    }
    public function userCanEdit(User $user)
    {
        return $user->isAdmin() || $this->user_id == $user->id;
    }

    public function favourited()
    {
        return (int) Favourite::where('user_id', Auth::id())
            ->where('post_id', $this->id)
            ->count();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Illuminate\Support\Facades\Auth;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

//        $posts = Post::all();
        $posts = Post::paginate(5);

//        $user = Auth::user();
//        $user->load('favourited');


        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        if(Auth::user()->role === 'sourcer'){
            return view('posts/create');
        }
        else{
          return redirect()->route('posts.index');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if ($request->hasFile('file')) {
            $image=$request->file('file');
            $imageName = $image->getClientOriginalName();
            $uniqueName = md5($imageName . microtime());
            $image->move(public_path('uploads'), $uniqueName);
        } else {
            return 'Cannot find file called';
        }
$path = '/uploads/';





        Post::create([
            'user_id' =>Auth::user()->id,
            'title' =>$request->title,
            'post_code' =>$request->post_code,
            'house_number' =>$request->house_number,
            'property_type' =>$request->property_type,
            'beds_no' => $request->beds_no,
            'bathrooms_no' => $request->bathrooms_no,
            'price' => $request->price,
            'commission' => $request->commission,
            'description' =>$request->description,
            'image_pathway'=>$path . $uniqueName,
        ]);

//    $post = new Post;
//    $post-> title = $request->title;
//    $post-> save();

        return redirect('/posts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $post = Post::findOrFail($id);

        return view('posts.show', compact('post'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //



        if(Auth::user()->role === 'sourcer'){
            $post = Post::findOrFail($id);

            return view('posts.edit', compact('post'));
        }
        else{
            return redirect('/posts');
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if ($request->hasFile('file')) {
            $image=$request->file('file');
            $imageName = $image->getClientOriginalName();
            $uniqueName = md5($imageName . microtime());
            $image->move(public_path('uploads'), $uniqueName);
        } else {
            return 'Cannot find file called';
        }
        $path = '/uploads/';

        //first we find the id
        $post = Post::findOrFail($id);

        //then we grab and update the object
        $post->update($request->all() + ['image_pathway' => $path . $uniqueName]);








        //return redirect to the page
        return redirect('/usersposts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $post = Post::findOrFail($id);

        $post->delete();

        return redirect('posts');


    }
    public function favouritePost(Post $post)
    {
        Auth::user()->favourites()->attach($post->id);

        return back();
    }

    public function unFavouritePost(Post $post)
    {
        Auth::user()->favourites()->detach($post->id);

        return back();
    }
    public function  authPosts()
    {
        $posts = Post::where('user_id','=',Auth::user()->id)->paginate(5);

        return view('posts/index', ['posts' => $posts]);
    }
    public function upload(Request $request)
    {
//        Read image
        $img = Post::make($request->file('image')->getPathName());
        $extension = $request->file('image')->getClientOriginalExtension();

    }

}

resources/views/posts/create.blade.php
@extends('layouts.app')



@section('content')
<div class="container">
    <h2>Create Post</h2>
    <form  enctype="multipart/form-data" method="post" action="/posts" class="create">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" placeholder="enter title" class="form-control">
            {{csrf_field()}}
        </div>
        <div class="form-inline">
            <div class="form-group">
                <label for="house_number">House Number</label>
                <input type="number" name="house_number" placeholder="27" class="form-control inline-form-input">
            </div>
            <div class="form-group form-check">
                <label for="post_code">Post code</label>
                <input type="text" name="post_code" placeholder="EX1 ABC" class="form-control inline-form-input">
            </div>
        </div>

        <div class="form-group">
            <label for="property_type">Property type</label>
            <select class="form-control" name="property_type">
                <option>House</option>
                <option>Flat</option>
                <option>Land</option>
                <option>Commercial</option>
                <option>Bungalow</option>
                <option>Other</option>
            </select>
        </div>
        <div class="form-group">
            <label for="beds_no">No. of beds</label>
            <select class="form-control" name="beds_no">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10+</option>
            </select>
        </div>
        <div class="form-group">
            <label for="bathrooms_no">No. of bathrooms</label>
            <select class="form-control" name="bathrooms_no">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10+</option>
            </select>
        </div>
        <div class="form-group">
            <label for="price">Price  £</label>
            <input type="number" name="price" placeholder="100000" class="form-control">
        </div>
        <div class="form-group">
            <label for="commission">Sourcer commission  £</label>
            <input type="number" name="commission" placeholder="5000" class="form-control">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" rows="3" placeholder="extra details..."></textarea>
        </div>
        <div class="form-group">
            <label for="exampleFormControlFile1">Upload an image</label>

            <input name="file" type="file" class="form-control-file" >
        </div>


        <button type="submit" class="btn btn-primary" name="submit">Submit</button>
    </form>

</div>








@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')



@section('content')

    <div class="container">
        <h2>Edit post</h2>
        <form  enctype="multipart/form-data" method="post" action="/posts/{{$post->id}}" class="create">
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group">
                <label for="title">Edit Title</label>
                <input type="text" name="title" placeholder="enter title" value="{{$post->title}}" class="form-control">
                {{csrf_field()}}
            </div>
            <div class="form-inline">
                <div class="form-group">
                    <label for="house_number">House Number</label>
                    <input type="number" name="house_number" placeholder="enter number" value="{{$post->house_number}}"class="form-control inline-form-input">
                </div>
                <div class="form-group form-check">
                    <label for="post_code">Post code</label>
                    <input type="text" name="post_code" placeholder="enter postCode" value="{{$post->post_code}}" class="form-control inline-form-input">
                </div>
            </div>

            <div class="form-group">
                <label for="property_type">Property type</label>
                <select class="form-control" name="property_type">
                    <option>House</option>
                    <option>Flat</option>
                    <option>Land</option>
                    <option>Commercial</option>
                    <option>Bungalow</option>
                    <option>Other</option>
                </select>
            </div>
            <div class="form-group">
                <label for="beds_no">No. of beds</label>
                <select class="form-control" name="beds_no">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                </select>
            </div>
            <div class="form-group">
                <label for="bathrooms_no">No. of bathrooms</label>
                <select class="form-control" name="bathrooms_no">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                </select>
            </div>
            <div class="form-group">
                <label for="price">Price £</label>
                <input type="number" name="price" placeholder="£100000" value="{{$post->price}}" class="form-control">
            </div>
            <div class="form-group">
                <label for="commission">Sourcer commission £</label>
                <input type="number" name="commission" placeholder="£5000" value="{{$post->commission}}" class="form-control">
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" name="description" rows="3"
                          placeholder="extra details...">{{$post->description}}</textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlFile1">Upload an image</label>

                <input name="file" type="file" class="form-control-file" >
            </div>


            <input type="submit" name="submit" value="UPDATE"
                   onclick="return confirm('Please confirm to update your listing')" class="btn">


        </form>
        <form method="post" action="/posts/{{$post->id}}">
            {{csrf_field()}}
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="DELETE"
                   onclick="return confirm('Are you sure you want to delete this listing?')" class="btn">

        </form>

    </div>





@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')



@section('content')


    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                    <div class="page-header">
                    @if(Request::url() ==='/usersposts/{user_id}')
                        <h2>i am working</h2>
                    @else
                            <h2>Listings currently available </h2>
                    @endif
                </div>
                @forelse ($posts as $post)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {{ $post->title }}

                        </div>

                        <div class="panel-body">


        <img src="{{$post->image_pathway}}">
                            {{--@if($post->property_type ==='House')--}}
                                {{--<img src="/images/house.jpeg">--}}
                            {{--@elseif($post->property_type ==='Flat')--}}
                                {{--<img src="/images/flat.jpg">--}}
                            {{--@elseif($post->property_type ==='Land')--}}
                                {{--<img src="/images/land1.jpeg">--}}
                            {{--@elseif($post->property_type ==='Bungalow')--}}
                                {{--<img src="/images/bungalow.jpg">--}}
                            {{--@elseif($post->property_type ==='Commercial')--}}
                                {{--<img src="/images/commercial.jpeg">--}}
                            {{--@else--}}
                                {{--<img src="/images/house.jpeg">--}}
                            {{--@endif--}}

                            <ul>

                                <li><i class="fas fa-bath listing-icon"></i>
                                    <p>{{$post->bathrooms_no}}</p></li>
                                <li><i class="fas fa-bed listing-icon"></i>
                                    <p>{{$post->beds_no}}</p></li>
                                <div class="price-p row">
                                    <div class="col-lg-4">
                                        <span class="red">Price:</span>
                                        <p> £{{$post->price}}</p>
                                    </div>
                                    <div class="col-lg-4">
                                        <span class="red">Commision:</span>
                                        <p> £{{$post->commission}}</p>
                                    </div>


                                </div>

                            </ul>
                        </div>
                        <div class="panel-links">
                            <p> {{$post->description}} <a href="{{route('posts.show', $post->id)}}"> ...read more</a>
                            </p>

                            <p>Listed by: <a href="{{url("/usersposts/$post->user_id")}}">{{ $post->user->name }}</a>
                            </p>

                        </div>


                        @if (Auth::check())
                            <div class="panel-footer">
                                <favourite
                                        post="{{ $post->id }}"
                                        favourited="{{ $post->favourited() ? 'true' : '' }}"
                                ></favourite>
                            </div>
                        @endif

                    </div>
                @empty
                    <p>No post created.</p>
                @endforelse
                <div class="row listing-links">
                    <button class="btn" onclick="goBack()">Go Back</button>

                    @if(Auth::user()->role === 'sourcer')
                        @if($posts->count() > 0)

                            <a class="btn new-listings" href="{{route('posts.create')}}">Create another new listing</a>
                        @else
                            <p>You haven't listed a property yet!</p>
                            <a href="{{route('posts.create')}}">Create your first listing here</a>
                        @endif

                    @endif
                </div>
                {{--<button class ="btn" onclick="goBack()">Go Back</button>--}}

                <div class="pagination-bar">
                    {{ $posts->links() }}

                </div>

            </div>
        </div>
    </div>


@endsection

resources/views/posts/myDeals.blade.php
@extends('layouts.app')



@section('content')
    {{--<div class="container">--}}
    {{--<div class="row">--}}
    {{--<div class="col-lg-12">--}}
    {{--<h2>Listings currently available</h2>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--<div class="row">--}}



    {{--<ul>--}}
    {{--@foreach($posts as $post)--}}


    {{--<li style="border: 1px solid black; list-style: none; height: 150px; width: 50%; margin: 10px auto">--}}


    {{--<h6>{{$post->title}}</h6>--}}
    {{--<a href="{{route('posts.show', $post->id)}}"><img src="../images/beautiful-house.jpg" style="height: 70%; float: left; margin-right:10px"></a>--}}
    {{--<ul>--}}
    {{--<li>Price: £{{$post->price}}</li>--}}
    {{--<li>Commision: £{{$post->commission}}</li>--}}
    {{--<li>Baths: {{$post->bathrooms_no}}</li>--}}
    {{--<li>Beds: {{$post->beds_no}}</li>--}}

    {{--</ul>--}}


    {{--<a href="{{route('posts.show', $post->id)}}">read more</a>--}}
    {{--<p>Listed by: <a href="{{url("/usersposts/$post->user_id")}}">{{ $post->user->name }}</a></p>--}}


    {{--add a user profile click from listing--}}
    {{--add a user name--}}



    {{--</li>--}}


    {{--@endforeach--}}

    {{--</ul>--}}
    {{--</div>--}}
    {{--<div class="row">--}}
    {{--@if(Auth::user()->role === 'sourcer')--}}
    {{--@if($posts->count() > 0)--}}

    {{--<a href="{{route('posts.create')}}">Create another new listing</a>--}}
    {{--@else--}}
    {{--<p>You haven't listed a poperty yet!</p>--}}
    {{--<a href="{{route('posts.create')}}">Create your first listing here</a>--}}
    {{--@endif--}}

    {{--@endif--}}
    {{--</div>--}}
    {{--</div>--}}


    {{--</div>--}}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">


                <div class="page-header">
                    <h2>Listings currently available </h2>
                </div>
                @forelse ($posts as $post)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {{ $post->title }}

                        </div>

                        <div class="panel-body">
                            <ul>

                                <li><i class="fas fa-bath listing-icon"></i>
                                    <p>{{$post->bathrooms_no}}</p></li>
                                <li><i class="fas fa-bed listing-icon"></i>
                                    <p>{{$post->beds_no}}</p></li>
                                <div class="price-p row">
                                    <div class="col-lg-4">
                                        <span class="red">Price:</span><p> £{{$post->price}}</p>
                                    </div>
                                    <div class="col-lg-4">
                                        <span class="red">Commision:</span><p> £{{$post->commission}}</p>
                                    </div>


                                </div>

                            </ul>
                        </div>
                        <div class="panel-links">
                            <p> {{$post->description}} <a href="{{route('posts.show', $post->id)}}"> ...read more</a>
                            </p>

                            <p>Listed by: <a href="{{url("/usersposts/$post->user_id")}}">{{ $post->user->name }}</a>
                            </p>

                        </div>


                        @if (Auth::check())
                            <div class="panel-footer">
                                <favourite
                                        post="{{ $post->id }}"
                                        favourited="{{ $post->favourited() ? 'true' : '' }}"
                                ></favourite>
                            </div>
                        @endif

                    </div>
                @empty
                    <p>No post created.</p>
                @endforelse
                <div class="row listing-links">
                    <button class="btn" onclick="goBack()">Go Back</button>

                    @if(Auth::user()->role === 'sourcer')
                        @if($posts->count() > 0)

                            <a class="btn new-listings" href="{{route('posts.create')}}">Create another new listing</a>
                        @else
                            <p>You haven't listed a poperty yet!</p>
                            <a href="{{route('posts.create')}}">Create your first listing here</a>
                        @endif

                    @endif
                </div>
                {{--<button class ="btn" onclick="goBack()">Go Back</button>--}}

                <div class="pagination-bar">
                    {{ $posts->links() }}

                </div>

            </div>
        </div>
    </div>


@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')



@section('content')
    <div class="container">


        <div class="container deal-details" style="border: 1px solid black">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#overview">Overview</a></li>
                <li><a data-toggle="tab" href="#metrics">Metrics</a></li>
            </ul>
            <div class="tab-content">
                <div id="overview" class="tab-pane fade in active">

                    <div class="row">
                        <h2>{{$post->title}}</h2>
                    </div>
                    <div class="row listing-pic">

                        <img src="{{$post->image_pathway}}">


                        {{--@if($post->property_type ==='House')--}}
                            {{--<img src="/images/house.jpeg">--}}
                        {{--@elseif($post->property_type ==='Flat')--}}
                            {{--<img src="/images/flat.jpg">--}}
                        {{--@elseif($post->property_type ==='Land')--}}
                            {{--<img src="/images/land1.jpeg">--}}
                        {{--@elseif($post->property_type ==='Bungalow')--}}
                            {{--<img src="/images/bungalow.jpg">--}}
                        {{--@elseif($post->property_type ==='Commercial')--}}
                            {{--<img src="/images/commercial.jpeg">--}}
                        {{--@else--}}
                            {{--<img src="/images/house.jpeg">--}}
                        {{--@endif--}}
                        <div class="col-lg-12">
                            <p><span class="red"> House Number:</span> {{$post->house_number}}</p>
                            <p><span class="red">Post Code: </span>{{$post->post_code}}</p>
                            <p><span class="red">Number of bathrooms:</span> {{$post->bathrooms_no}}</p>
                            <p><span class="red">Number of beds: </span>{{$post->beds_no}}</p>
                            <p><span class="red">Price: £ </span>{{$post->price}}</p>
                            <p><span class="red">Commission: £ </span>{{$post->commission}}</p>
                            <p><span class="red">Property type:</span> {{$post->property_type}}</p>
                            <p><span class="red">Description:</span> {{$post->description}}</p>
                        </div>
                    </div>
                </div>
                <div id="metrics" class="tab-pane fade in">
                    <div class="row">
                        <h2>Data Overview</h2>
                    </div>
                    <div class="row">
<p>ldnweidnwe</p>










                    </div>
                </div>


            </div>

            @if(Auth::user()->can('update', $post))
                <div class="row deal-sourcer">
                    <div class="col-lg-12">
                        <p><a href="{{route('posts.edit',$post->id)}}">Edit this listing</a></p>
                    </div>
                    <a class="user-sellers" href="{{url("/usersposts")}}">See all of your posts</a>
                </div>
            @else
                <div class="row deal-sourcer">
                    <div class="col-lg-4">
                        <favourite id="favs-link-dissapear"
                                   post="{{ $post->id }}"
                                   favourited="{{ $post->favourited() ? 'true' : '' }}"
                        ></favourite>
                    </div>

                    {{--<a class="user-sellers" href="{{url("/usersPosts/$post->user_id")}}">See all posts by <span--}}
                    {{--class="user">{{ $post->user->name }} </span></a>--}}
                    <div class="col-lg-4">
                        <a href="{{url("/usersposts/$post->user_id")}}" class="user-sellers"> <span class="user">  see all posts by {{ $post->user->name }}</span></a>

                    </div>
                    <div class="col-lg-4">
                        <a href="#"><i class="far fa-envelope"></i></a>
                    </div>

                </div>
            @endif
        </div>

    </div>

@endsection
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>